const SPREADSHEET_ID='1pT8L0Eq-x-My6UmcgjmHOZmk19WgiNXxLZ_n4Bq6MB8';
const SHEETS=['길드창고📦','길드창고'];
const body=document.getElementById('warehouseBody'); const count=document.getElementById('warehouseCount');
const search=document.getElementById('warehouseSearch'); const typeSelect=document.getElementById('warehouseType'); const statusSelect=document.getElementById('warehouseStatus');
let items=[];
function clean(v){return String(v??'').replace(/\u00a0/g,' ').trim();}
function toNumber(v){const n=Number(clean(v).replace(/,/g,'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0;}
function format(v){return Math.floor(toNumber(v)).toLocaleString('ko-KR');}
function escapeHtml(v){return clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'){if(quoted&&next==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);if(row.some(v=>clean(v)))rows.push(row);row=[];cell='';}else cell+=ch;}row.push(cell);if(row.some(v=>clean(v)))rows.push(row);return rows;}
async function fetchSheet(){let last;for(const sheet of SHEETS){try{const url=`https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheet)}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${sheet}: ${r.status}`);const text=await r.text();if(/<!doctype html/i.test(text))throw new Error(`${sheet}: CSV 응답 아님`);const rows=parseCsv(text);if(!rows.length)throw new Error(`${sheet}: 빈 시트`);return rows;}catch(e){last=e;}}throw last||new Error('길드창고를 불러오지 못했습니다.');}
function read(rows){const h=rows.findIndex(row=>row.some(v=>clean(v).replace(/\s+/g,'').includes('아이템명')));if(h<0)return[];return rows.slice(h+1).map(row=>({number:clean(row[0]),grade:clean(row[1]),type:clean(row[2]),job:clean(row[3]),name:clean(row[4]),total:toNumber(row[5]),remaining:toNumber(row[6]),price:toNumber(row[7]),status:clean(row[8])})).filter(x=>x.name);}
function render(rows){count.textContent=rows.length.toLocaleString('ko-KR');if(!rows.length){body.innerHTML='<tr><td colspan="9">검색 결과가 없습니다.</td></tr>';return;}body.innerHTML=rows.map(x=>`<tr><td>${escapeHtml(x.number)}</td><td><span class="grade-badge">${escapeHtml(x.grade||'-')}</span></td><td>${escapeHtml(x.type||'-')}</td><td>${escapeHtml(x.job||'-')}</td><td class="warehouse-name">${escapeHtml(x.name)}</td><td>${format(x.total)}</td><td class="warehouse-stock">${format(x.remaining)}</td><td>${format(x.price)}</td><td><span class="warehouse-status ${x.status==='보관중'?'stock-active':''}">${escapeHtml(x.status||'-')}</span></td></tr>`).join('');}
function apply(){const q=clean(search.value).toLocaleLowerCase('ko-KR'),type=typeSelect.value,status=statusSelect.value;const rows=items.filter(x=>(!q||[x.name,x.grade,x.type,x.job].some(v=>v.toLocaleLowerCase('ko-KR').includes(q)))&&(type==='전체'||x.type===type)&&(status==='전체'||x.status===status)&&(status!=='보관중'||x.remaining>0)).sort((a,b)=>Number(a.number)-Number(b.number)||a.name.localeCompare(b.name,'ko'));render(rows);}
async function load(){try{items=read(await fetchSheet());apply();}catch(e){count.textContent='-';body.innerHTML=`<tr><td colspan="9">${escapeHtml(e.message||'길드창고를 불러오지 못했습니다.')}</td></tr>`;}}
search.addEventListener('input',apply);typeSelect.addEventListener('change',apply);statusSelect.addEventListener('change',apply);load();